
Validation sanity check:   0% 0/2 [00:00<?, ?it/s]
  | Name      | Type          | Params
--------------------------------------------
0 | encoder   | BEiT3D        | 86.6 M
1 | decoder   | UPerHead      | 74.9 M
2 | criterion | DiceFocalLoss | 0
--------------------------------------------
161 M     Trainable params
0         Non-trainable params
161 M     Total params
646.207   Total estimated model params size (MB)
/usr/local/lib/python3.8/site-packages/torch/nn/functional.py:3060: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.

Epoch 0:   0% 0/1728 [00:00<00:00, 6393.76it/s]
/gdrive/MyDrive/TransSeg/src/utils.py:317: RuntimeWarning: invalid value encountered in true_divide
  acc = total_area_intersect / total_area_label








































































Epoch 0:  84% 1460/1728 [41:18<07:34,  1.70s/it, loss=0.443, v_num=ya06]















Validating: 100% 271/271 [02:43<00:00,  1.67it/s]
/usr/local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:216: UserWarning: Please also save or load the state of the optimizer when saving or loading the scheduler.










































































Epoch 1:  84% 1460/1728 [40:32<07:26,  1.67s/it, loss=0.361, v_num=ya06]

























































































Epoch 2:  84% 1460/1728 [40:31<07:26,  1.66s/it, loss=0.435, v_num=ya06]
























































































Epoch 3:  84% 1460/1728 [40:33<07:26,  1.67s/it, loss=0.382, v_num=ya06]


























































































Epoch 4:  84% 1460/1728 [40:32<07:26,  1.67s/it, loss=0.412, v_num=ya06]
























































































Epoch 5:  84% 1460/1728 [40:31<07:26,  1.66s/it, loss=0.31, v_num=ya06]
























































































Epoch 6:  84% 1460/1728 [40:27<07:25,  1.66s/it, loss=0.358, v_num=ya06]

























































































Epoch 7:  84% 1460/1728 [40:33<07:26,  1.67s/it, loss=0.407, v_num=ya06]























Epoch 8:   8% 140/1728 [03:56<44:26,  1.68s/it, loss=0.414, v_num=ya06]
/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1051: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...

Epoch 8:   8% 140/1728 [03:56<44:26,  1.68s/it, loss=0.414, v_num=ya06]Loading data config from data/msd/processed/Task09_Spleen//dataset_5slices.json...
/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:423: LightningDeprecationWarning: DataModule.prepare_data has already been called, so it will not be called again. In v1.6 this behavior will change to always call DataModule.prepare_data.
  rank_zero_deprecation(
Global seed set to 1234

Loading dataset:  98% 63/64 [00:04<00:00, 18.76it/s]

Loading dataset:  98% 63/64 [00:04<00:00, 15.11it/s]


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0] 13.59it/s]
# Train: 2914, # Val: 542, # Test: 194...
Epoch 8:   9% 160/1728 [04:35<44:39,  1.71s/it, loss=0.414, v_num=ya06]



Validating:  22% 60/271 [00:37<02:11,  1.60it/s]
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    train(args)
  File "main.py", line 123, in train
    trainer.validate(datamodule=dm)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 627, in validate
    results = self._run(model)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_evaluating(self)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 95, in start_evaluating
    self.training_type_plugin.start_evaluating(trainer)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 165, in start_evaluating
    self._results = trainer.run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 997, in run_stage
    return self._run_evaluate()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1083, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 392, in validation_step
    return self.model(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/gdrive/MyDrive/TransSeg/src/model.py", line 265, in validation_step
    "loss": loss.item(),
KeyboardInterrupt